### PR TITLE
cd: update workflow to generate an index and bundle it in the wheel

### PR DESCRIPTION
**Pull request by jcfr**
This pull request was created directly from a branch published into the upstream repo to workaround the fact secret can not be used (by default) from pull request created from fork.

It is based on:
* https://github.com/ImagingDataCommons/idc-index-data/pull/5

### CODE REVIEW

**Comment by fedorov** [comment]
@jcfr is this PR ready for review/merge?

**Comment by jcfr** [comment]
This is ready for final review, support for bumping the version using `nox -s bump` will be added in a follow-up pull request.

It should be integrated using `Squash & Merge` specifying the following commit message:

```
feat: Add support for generating and bundling index files during wheel build

This commit introduces a helper Python script to facilitate the generation of
index files, namely `idc_index.csv.zip` and `idc_index.parquet`. Additionally,
it updates the build system to incorporate these index files into the generated
wheel package.

Update the build system to include new CMake options:
`IDC_INDEX_DATA_GENERATE_CSV_ARCHIVE` and `IDC_INDEX_DATA_GENERATE_PARQUET`,
allowing to specify whether to generate CSV archives and Parquet files respectively.
Currently, only the compressed CSV index file is generated and bundled.

Enhance the GitHub workflows by adding a step for authenticating to the Google
Cloud Platform (GCP) using the secret variable `SERVICE_ACCOUNT_KEY` associated
with the repository.

Remove support for `pypi-3.10` due to unresponsive runners while running
the command `python -m pip install .[test]`.

Adjust the `setuptools_scm` version scheme to maintain the development package version
consistent with the table version. Instead of setting the development package version
to the next one, set it by appending `.post1.devN`, where `N` represents the number of
commits following the most recent tag.

Co-authored-by: Andrey Fedorov <andrey.fedorov@gmail.com>
Co-authored-by: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>
```

**Comment by vkt1414** [comment]
Thank you very much @jcfr ! 
I learned a lot as this PR evolved.

Only thing is I do not know if the boolean value for parquet is passed along to the index manager properly, as it seem to generate both csv and parquet although the latter is disabled in cmakelists.

**Comment by jcfr** [comment]
This last commit should fix the following ...

image

**Comment by jcfr** [comment]
There is one more tweak I would like to add and will take care of this later .. have to head out now :rocket:

**Review by vkt1414 — APPROVED** [review]

**Comment by jcfr** [comment]
Moving forward with the integration, additional improvements and fixes will be integrated in follow-up pull requests.

**Comment by jcfr** [comment]
Unclear why I get the message `The base branch does not allow updates`, I updated a GitHub discussion[^1]  where this was mentioned and will move forward with the integration bypassing the checks.

### Status of the pull request before integration

image


[^1]: https://github.com/orgs/community/discussions/113172#discussioncomment-8955258

**Pull request merged**
