### PR TITLE
enh: simplify the query by using aws_bucket

### PR DESCRIPTION
**Pull request by fedorov**
This way we avoid parsing bucket name from aws_url

### CODE REVIEW

**Comment by vkt1414** [comment]
There's an even more precise way! We do have `series_aws_url` directly in dicom_all. We still need to concat * at the end.

image

**Review by vkt1414 — APPROVED** [review]

**Comment by fedorov** [comment]
Ah, I missed it!

But I think we should revisit this to be more precise. I don't think it is good to change the value of `aws_series_url` but adding * - instead I think we should add it on the fly while building the manifest or `s5cmd` download operation. Otherwise it is very confusing that the value is different between idc-index and BQ index.

**Comment by vkt1414** [comment]
Agree! Should we create an issue to track or just go ahead and create another PR? as we are yet to move to parquet in idc-index in https://github.com/ImagingDataCommons/idc-index/pull/57 ?

**Comment by fedorov** [comment]
I suggest let's move to Parquet first, then update to v18, and then deal with other issues.

**Pull request merged**
